// This file is part of OpenSoundLab, which is based on SoundStage VR.
//
// Copyright © 2020-2024 OSLLv1 Spherical Labs OpenSoundLab
//
// OpenSoundLab is licensed under the OpenSoundLab License Agreement (OSLLv1).
// You may obtain a copy of the License at
// https://github.com/SphericalLabs/OpenSoundLab/LICENSE-OSLLv1.md
//
// By using, modifying, or distributing this software, you agree to be bound by the terms of the license.
//
//
// Copyright © 2020 Apache 2.0 Maximilian Maroe SoundStage VR
// Copyright © 2019-2020 Apache 2.0 James Surine SoundStage VR
// Copyright © 2017 Apache 2.0 Google LLC SoundStage VR
//
// Licensed under the Apache License, Version 2.0 (the "License");
// You may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.0
//     from Assets/OSLInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/OSLInput.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @OSLInput : IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @OSLInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""OSLInput"",
    ""maps"": [
        {
            ""name"": ""Patcher"",
            ""id"": ""fa0e3d9e-1417-446a-b28e-db7409fca285"",
            ""actions"": [
                {
                    ""name"": ""PrimaryLeft"",
                    ""type"": ""Button"",
                    ""id"": ""e6c9ecaf-b2ef-493b-b7eb-3305dc359157"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryRight"",
                    ""type"": ""Button"",
                    ""id"": ""b1dd8378-1cf0-4c93-a1ed-4a65ecfe40e9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryLeft"",
                    ""type"": ""Button"",
                    ""id"": ""cfe2a8e1-0def-4b73-9835-7999d7775914"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryRight"",
                    ""type"": ""Button"",
                    ""id"": ""0284a21b-ad71-4fdf-ab6c-d2cf9970840a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GripLeft"",
                    ""type"": ""Value"",
                    ""id"": ""8c80dbb2-e4df-4247-a62f-a9443cb1a57a"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GripRight"",
                    ""type"": ""Value"",
                    ""id"": ""95bc30e0-54ac-4b4e-97e9-af5ac3958eef"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TriggerLeft"",
                    ""type"": ""Button"",
                    ""id"": ""0b5b3bc8-f9ea-460f-8591-9c0e32cce049"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TriggerRight"",
                    ""type"": ""Button"",
                    ""id"": ""59544473-b7c3-4794-a054-d2f00baf676c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TriggerLeftAnalog"",
                    ""type"": ""Value"",
                    ""id"": ""733ed998-da93-473b-b390-08ebf6371596"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TriggerRightAnalog"",
                    ""type"": ""Value"",
                    ""id"": ""3d23a1f9-b236-4ce5-af3a-9be8422f3204"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""be1bdf47-24c3-4128-be97-61de38913547"",
                    ""path"": ""<XRController>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3452e574-b40a-4b90-acf7-27cf147755c9"",
                    ""path"": ""<XRController>{LeftHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c0698d6-a459-49d2-809d-51d63aaa94ce"",
                    ""path"": ""<XRController>{LeftHand}/gripButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GripLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d135410e-b60a-4c99-bf76-1522864a3612"",
                    ""path"": ""<XRController>{LeftHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""80ca9fb8-b10b-4b0b-8563-ebb23963f059"",
                    ""path"": ""<XRController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5754cf6e-9933-4238-9d51-1aab7c3ea138"",
                    ""path"": ""<XRController>{RightHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f96c9781-0c26-43d0-9bef-b7c8934d0615"",
                    ""path"": ""<XRController>{RightHand}/gripButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GripRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fb73339d-971e-4352-b16a-64660a902881"",
                    ""path"": ""<XRController>{RightHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4dc7aed-fe51-40f6-92d7-49807ed0ac07"",
                    ""path"": ""<XRController>{LeftHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerLeftAnalog"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77246433-0ab3-4bc0-ab9b-8d67ffd3a65f"",
                    ""path"": ""<XRController>{RightHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerRightAnalog"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Patcher
        m_Patcher = asset.FindActionMap("Patcher", throwIfNotFound: true);
        m_Patcher_PrimaryLeft = m_Patcher.FindAction("PrimaryLeft", throwIfNotFound: true);
        m_Patcher_PrimaryRight = m_Patcher.FindAction("PrimaryRight", throwIfNotFound: true);
        m_Patcher_SecondaryLeft = m_Patcher.FindAction("SecondaryLeft", throwIfNotFound: true);
        m_Patcher_SecondaryRight = m_Patcher.FindAction("SecondaryRight", throwIfNotFound: true);
        m_Patcher_GripLeft = m_Patcher.FindAction("GripLeft", throwIfNotFound: true);
        m_Patcher_GripRight = m_Patcher.FindAction("GripRight", throwIfNotFound: true);
        m_Patcher_TriggerLeft = m_Patcher.FindAction("TriggerLeft", throwIfNotFound: true);
        m_Patcher_TriggerRight = m_Patcher.FindAction("TriggerRight", throwIfNotFound: true);
        m_Patcher_TriggerLeftAnalog = m_Patcher.FindAction("TriggerLeftAnalog", throwIfNotFound: true);
        m_Patcher_TriggerRightAnalog = m_Patcher.FindAction("TriggerRightAnalog", throwIfNotFound: true);
    }

    ~@OSLInput()
    {
        UnityEngine.Debug.Assert(!m_Patcher.enabled, "This will cause a leak and performance issues, OSLInput.Patcher.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Patcher
    private readonly InputActionMap m_Patcher;
    private List<IPatcherActions> m_PatcherActionsCallbackInterfaces = new List<IPatcherActions>();
    private readonly InputAction m_Patcher_PrimaryLeft;
    private readonly InputAction m_Patcher_PrimaryRight;
    private readonly InputAction m_Patcher_SecondaryLeft;
    private readonly InputAction m_Patcher_SecondaryRight;
    private readonly InputAction m_Patcher_GripLeft;
    private readonly InputAction m_Patcher_GripRight;
    private readonly InputAction m_Patcher_TriggerLeft;
    private readonly InputAction m_Patcher_TriggerRight;
    private readonly InputAction m_Patcher_TriggerLeftAnalog;
    private readonly InputAction m_Patcher_TriggerRightAnalog;
    /// <summary>
    /// Provides access to input actions defined in input action map "Patcher".
    /// </summary>
    public struct PatcherActions
    {
        private @OSLInput m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PatcherActions(@OSLInput wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Patcher/PrimaryLeft".
        /// </summary>
        public InputAction @PrimaryLeft => m_Wrapper.m_Patcher_PrimaryLeft;
        /// <summary>
        /// Provides access to the underlying input action "Patcher/PrimaryRight".
        /// </summary>
        public InputAction @PrimaryRight => m_Wrapper.m_Patcher_PrimaryRight;
        /// <summary>
        /// Provides access to the underlying input action "Patcher/SecondaryLeft".
        /// </summary>
        public InputAction @SecondaryLeft => m_Wrapper.m_Patcher_SecondaryLeft;
        /// <summary>
        /// Provides access to the underlying input action "Patcher/SecondaryRight".
        /// </summary>
        public InputAction @SecondaryRight => m_Wrapper.m_Patcher_SecondaryRight;
        /// <summary>
        /// Provides access to the underlying input action "Patcher/GripLeft".
        /// </summary>
        public InputAction @GripLeft => m_Wrapper.m_Patcher_GripLeft;
        /// <summary>
        /// Provides access to the underlying input action "Patcher/GripRight".
        /// </summary>
        public InputAction @GripRight => m_Wrapper.m_Patcher_GripRight;
        /// <summary>
        /// Provides access to the underlying input action "Patcher/TriggerLeft".
        /// </summary>
        public InputAction @TriggerLeft => m_Wrapper.m_Patcher_TriggerLeft;
        /// <summary>
        /// Provides access to the underlying input action "Patcher/TriggerRight".
        /// </summary>
        public InputAction @TriggerRight => m_Wrapper.m_Patcher_TriggerRight;
        /// <summary>
        /// Provides access to the underlying input action "Patcher/TriggerLeftAnalog".
        /// </summary>
        public InputAction @TriggerLeftAnalog => m_Wrapper.m_Patcher_TriggerLeftAnalog;
        /// <summary>
        /// Provides access to the underlying input action "Patcher/TriggerRightAnalog".
        /// </summary>
        public InputAction @TriggerRightAnalog => m_Wrapper.m_Patcher_TriggerRightAnalog;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Patcher; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PatcherActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PatcherActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PatcherActions" />
        public void AddCallbacks(IPatcherActions instance)
        {
            if (instance == null || m_Wrapper.m_PatcherActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PatcherActionsCallbackInterfaces.Add(instance);
            @PrimaryLeft.started += instance.OnPrimaryLeft;
            @PrimaryLeft.performed += instance.OnPrimaryLeft;
            @PrimaryLeft.canceled += instance.OnPrimaryLeft;
            @PrimaryRight.started += instance.OnPrimaryRight;
            @PrimaryRight.performed += instance.OnPrimaryRight;
            @PrimaryRight.canceled += instance.OnPrimaryRight;
            @SecondaryLeft.started += instance.OnSecondaryLeft;
            @SecondaryLeft.performed += instance.OnSecondaryLeft;
            @SecondaryLeft.canceled += instance.OnSecondaryLeft;
            @SecondaryRight.started += instance.OnSecondaryRight;
            @SecondaryRight.performed += instance.OnSecondaryRight;
            @SecondaryRight.canceled += instance.OnSecondaryRight;
            @GripLeft.started += instance.OnGripLeft;
            @GripLeft.performed += instance.OnGripLeft;
            @GripLeft.canceled += instance.OnGripLeft;
            @GripRight.started += instance.OnGripRight;
            @GripRight.performed += instance.OnGripRight;
            @GripRight.canceled += instance.OnGripRight;
            @TriggerLeft.started += instance.OnTriggerLeft;
            @TriggerLeft.performed += instance.OnTriggerLeft;
            @TriggerLeft.canceled += instance.OnTriggerLeft;
            @TriggerRight.started += instance.OnTriggerRight;
            @TriggerRight.performed += instance.OnTriggerRight;
            @TriggerRight.canceled += instance.OnTriggerRight;
            @TriggerLeftAnalog.started += instance.OnTriggerLeftAnalog;
            @TriggerLeftAnalog.performed += instance.OnTriggerLeftAnalog;
            @TriggerLeftAnalog.canceled += instance.OnTriggerLeftAnalog;
            @TriggerRightAnalog.started += instance.OnTriggerRightAnalog;
            @TriggerRightAnalog.performed += instance.OnTriggerRightAnalog;
            @TriggerRightAnalog.canceled += instance.OnTriggerRightAnalog;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PatcherActions" />
        private void UnregisterCallbacks(IPatcherActions instance)
        {
            @PrimaryLeft.started -= instance.OnPrimaryLeft;
            @PrimaryLeft.performed -= instance.OnPrimaryLeft;
            @PrimaryLeft.canceled -= instance.OnPrimaryLeft;
            @PrimaryRight.started -= instance.OnPrimaryRight;
            @PrimaryRight.performed -= instance.OnPrimaryRight;
            @PrimaryRight.canceled -= instance.OnPrimaryRight;
            @SecondaryLeft.started -= instance.OnSecondaryLeft;
            @SecondaryLeft.performed -= instance.OnSecondaryLeft;
            @SecondaryLeft.canceled -= instance.OnSecondaryLeft;
            @SecondaryRight.started -= instance.OnSecondaryRight;
            @SecondaryRight.performed -= instance.OnSecondaryRight;
            @SecondaryRight.canceled -= instance.OnSecondaryRight;
            @GripLeft.started -= instance.OnGripLeft;
            @GripLeft.performed -= instance.OnGripLeft;
            @GripLeft.canceled -= instance.OnGripLeft;
            @GripRight.started -= instance.OnGripRight;
            @GripRight.performed -= instance.OnGripRight;
            @GripRight.canceled -= instance.OnGripRight;
            @TriggerLeft.started -= instance.OnTriggerLeft;
            @TriggerLeft.performed -= instance.OnTriggerLeft;
            @TriggerLeft.canceled -= instance.OnTriggerLeft;
            @TriggerRight.started -= instance.OnTriggerRight;
            @TriggerRight.performed -= instance.OnTriggerRight;
            @TriggerRight.canceled -= instance.OnTriggerRight;
            @TriggerLeftAnalog.started -= instance.OnTriggerLeftAnalog;
            @TriggerLeftAnalog.performed -= instance.OnTriggerLeftAnalog;
            @TriggerLeftAnalog.canceled -= instance.OnTriggerLeftAnalog;
            @TriggerRightAnalog.started -= instance.OnTriggerRightAnalog;
            @TriggerRightAnalog.performed -= instance.OnTriggerRightAnalog;
            @TriggerRightAnalog.canceled -= instance.OnTriggerRightAnalog;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PatcherActions.UnregisterCallbacks(IPatcherActions)" />.
        /// </summary>
        /// <seealso cref="PatcherActions.UnregisterCallbacks(IPatcherActions)" />
        public void RemoveCallbacks(IPatcherActions instance)
        {
            if (m_Wrapper.m_PatcherActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PatcherActions.AddCallbacks(IPatcherActions)" />
        /// <seealso cref="PatcherActions.RemoveCallbacks(IPatcherActions)" />
        /// <seealso cref="PatcherActions.UnregisterCallbacks(IPatcherActions)" />
        public void SetCallbacks(IPatcherActions instance)
        {
            foreach (var item in m_Wrapper.m_PatcherActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PatcherActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PatcherActions" /> instance referencing this action map.
    /// </summary>
    public PatcherActions @Patcher => new PatcherActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Patcher" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PatcherActions.AddCallbacks(IPatcherActions)" />
    /// <seealso cref="PatcherActions.RemoveCallbacks(IPatcherActions)" />
    public interface IPatcherActions
    {
        /// <summary>
        /// Method invoked when associated input action "PrimaryLeft" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPrimaryLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PrimaryRight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPrimaryRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SecondaryLeft" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSecondaryLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SecondaryRight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSecondaryRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "GripLeft" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnGripLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "GripRight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnGripRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TriggerLeft" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTriggerLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TriggerRight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTriggerRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TriggerLeftAnalog" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTriggerLeftAnalog(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TriggerRightAnalog" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTriggerRightAnalog(InputAction.CallbackContext context);
    }
}
