#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/common.sh"

SOURCE_ASSETS="$OR_SUBMODULE_DIR/platforms/unity/UnityIntegration/Assets/ResonanceAudio"
PACKAGE_ROOT="$OR_BUILD_DIR/Package"
EXPECTED_PACKAGE_ROOT="$OR_BUILD_DIR/Package"
LEGACY_DEST_ASSETS="$OR_PROJECT_DIR/Assets/ResonanceAudio"
PACKAGE_NOTICE_DIR="$PACKAGE_ROOT/ThirdPartyNotices"

or_require_submodule
or_need_command rsync

if [ ! -d "$SOURCE_ASSETS" ]; then
    or_fail "OpenResonance Unity assets are missing: $SOURCE_ASSETS"
fi
if [ "$PACKAGE_ROOT" != "$EXPECTED_PACKAGE_ROOT" ]; then
    or_fail "Refusing to install OpenResonance package to unexpected path: $PACKAGE_ROOT"
fi
case "$PACKAGE_ROOT" in
    "$OR_BUILD_DIR"/Package) ;;
    *)
        or_fail "Refusing to run rsync --delete outside the OpenResonance generated package folder: $PACKAGE_ROOT"
        ;;
esac
if [ "$PACKAGE_ROOT" = "/" ] || [ "$PACKAGE_ROOT" = "$OR_PROJECT_DIR" ] || [ "$PACKAGE_ROOT" = "$OR_BUILD_DIR" ]; then
    or_fail "Refusing unsafe OpenResonance package destination: $PACKAGE_ROOT"
fi

or_log "Generating OpenResonance Unity package without demos"
mkdir -p "$PACKAGE_ROOT"

rsync -a --delete --delete-excluded \
    --exclude "Demos/" \
    --exclude "Demos.meta" \
    --exclude ".DS_Store" \
    --exclude "Resources/ResonanceAudioMixer.mixer" \
    --exclude "Resources/ResonanceAudioMixer.mixer.meta" \
    "$SOURCE_ASSETS/" \
    "$PACKAGE_ROOT/"

cat > "$PACKAGE_ROOT/package.json" <<'JSON'
{
  "name": "io.sphericals.openresonance",
  "version": "0.1.0",
  "displayName": "OpenResonance",
  "description": "Generated OpenSoundLab package for the OpenResonance Unity integration.",
  "unity": "2022.3",
  "hideInEditor": false,
  "keywords": [
    "opensoundlab",
    "openresonance",
    "spatial-audio"
  ],
  "author": {
    "name": "Sphericals"
  }
}
JSON

cat > "$PACKAGE_ROOT/README.md" <<'EOF'
# OpenResonance

This package is generated by OpenSoundLab's `OpenResonanceBuild/install_unity_package.sh`.
Do not edit generated package contents directly; rebuild OpenResonance and regenerate the package instead.

License and third-party notice files are generated into this package as
`LICENSE`, `NOTICE`, `THIRD_PARTY_NOTICES.md` and `ThirdPartyNotices/`.
EOF

copy_package_notice() {
    local source_path="$1"
    local destination_name="$2"

    if [ -f "$source_path" ]; then
        cp "$source_path" "$PACKAGE_NOTICE_DIR/$destination_name"
    else
        echo "Warning: OpenResonance notice source missing: $source_path"
    fi
}

mkdir -p "$PACKAGE_NOTICE_DIR"
cp "$OR_SUBMODULE_DIR/LICENSE" "$PACKAGE_ROOT/LICENSE"
if [ -f "$OR_SUBMODULE_DIR/NOTICE" ]; then
    cp "$OR_SUBMODULE_DIR/NOTICE" "$PACKAGE_ROOT/NOTICE"
else
    echo "Warning: OpenResonance notice source missing: $OR_SUBMODULE_DIR/NOTICE"
fi
if [ -f "$OR_SUBMODULE_DIR/THIRD_PARTY_NOTICES.md" ]; then
    cp "$OR_SUBMODULE_DIR/THIRD_PARTY_NOTICES.md" "$PACKAGE_ROOT/THIRD_PARTY_NOTICES.md"
else
    echo "Warning: OpenResonance notice source missing: $OR_SUBMODULE_DIR/THIRD_PARTY_NOTICES.md"
fi

copy_package_notice "$OR_SUBMODULE_DIR/third_party/eigen/LICENSE" "eigen-LICENSE.txt"
copy_package_notice "$OR_SUBMODULE_DIR/third_party/eigen/COPYING.README" "eigen-COPYING.README.txt"
copy_package_notice "$OR_SUBMODULE_DIR/third_party/eigen/COPYING.MPL2" "eigen-COPYING.MPL2.txt"
copy_package_notice "$OR_SUBMODULE_DIR/third_party/eigen/COPYING.BSD" "eigen-COPYING.BSD.txt"
copy_package_notice "$OR_SUBMODULE_DIR/third_party/eigen/COPYING.APACHE" "eigen-COPYING.APACHE.txt"
copy_package_notice "$OR_SUBMODULE_DIR/third_party/eigen/COPYING.MINPACK" "eigen-COPYING.MINPACK.txt"
copy_package_notice "$OR_SUBMODULE_DIR/third_party/SADIE_hrtf_database/LICENSE" "sadie-hrtf-LICENSE.txt"
copy_package_notice "$OR_SUBMODULE_DIR/third_party/ogg/COPYING" "ogg-COPYING.txt"
copy_package_notice "$OR_SUBMODULE_DIR/third_party/vorbis/COPYING" "vorbis-COPYING.txt"
copy_package_notice "$OR_SUBMODULE_DIR/third_party/embree/LICENSE.txt" "embree-LICENSE.txt"
copy_package_notice "$OR_SUBMODULE_DIR/third_party/nativeaudioplugins/LICENSE" "nativeaudioplugins-LICENSE.txt"

if [ -f "$OR_SUBMODULE_DIR/third_party/pffft/pffft.h" ]; then
    sed -n '1,/^\*\//p' "$OR_SUBMODULE_DIR/third_party/pffft/pffft.h" > "$PACKAGE_NOTICE_DIR/pffft-FFTPACK-license.txt"
else
    echo "Warning: OpenResonance notice source missing: $OR_SUBMODULE_DIR/third_party/pffft/pffft.h"
fi

cat > "$PACKAGE_ROOT/Scripts/ResonanceAudio.Runtime.asmdef" <<'JSON'
{
    "name": "ResonanceAudio.Runtime",
    "rootNamespace": "",
    "references": [],
    "includePlatforms": [],
    "excludePlatforms": [],
    "allowUnsafeCode": false,
    "overrideReferences": false,
    "precompiledReferences": [],
    "autoReferenced": true,
    "defineConstraints": [],
    "versionDefines": [],
    "noEngineReferences": false
}
JSON

cat > "$PACKAGE_ROOT/Scripts/ResonanceAudio.Runtime.asmdef.meta" <<'EOF'
fileFormatVersion: 2
guid: 92dbad0359f94f3c8a47c22f74310352
AssemblyDefinitionImporter:
  externalObjects: {}
  userData: 
  assetBundleName: 
  assetBundleVariant: 
EOF

cat > "$PACKAGE_ROOT/Editor/ResonanceAudio.Editor.asmdef" <<'JSON'
{
    "name": "ResonanceAudio.Editor",
    "rootNamespace": "",
    "references": [
        "ResonanceAudio.Runtime"
    ],
    "includePlatforms": [
        "Editor"
    ],
    "excludePlatforms": [],
    "allowUnsafeCode": false,
    "overrideReferences": false,
    "precompiledReferences": [],
    "autoReferenced": true,
    "defineConstraints": [],
    "versionDefines": [],
    "noEngineReferences": false
}
JSON

cat > "$PACKAGE_ROOT/Editor/ResonanceAudio.Editor.asmdef.meta" <<'EOF'
fileFormatVersion: 2
guid: eb0c1d3209f84899a9ba84f969f54c86
AssemblyDefinitionImporter:
  externalObjects: {}
  userData: 
  assetBundleName: 
  assetBundleVariant: 
EOF

if [ -d "$OR_STAGING_ROOT" ]; then
    or_log "Installing staged OpenResonance native plugins into package"
    if [ "$#" -gt 0 ]; then
        for target_name in "$@"; do
            plugins_dir="$OR_STAGING_ROOT/$target_name/unity/Assets/ResonanceAudio/Plugins"
            if [ -d "$plugins_dir" ]; then
                rsync -a "$plugins_dir/" "$PACKAGE_ROOT/Plugins/"
            else
                echo "Skipping OpenResonance staged plugins because target is missing: $target_name"
            fi
        done
    else
        while IFS= read -r -d '' plugins_dir; do
            rsync -a "$plugins_dir/" "$PACKAGE_ROOT/Plugins/"
        done < <(find "$OR_STAGING_ROOT" -path "*/unity/Assets/ResonanceAudio/Plugins" -type d -print0)
    fi
fi

"$OR_BUILD_DIR/restore_plugin_meta_templates.sh"

if [ -d "$LEGACY_DEST_ASSETS" ]; then
    echo "Warning: legacy OpenResonance Assets install still exists: $LEGACY_DEST_ASSETS"
    echo "Remove it before opening Unity to avoid duplicate ResonanceAudio scripts and plugins."
fi

echo "Generated OpenResonance Unity package at $PACKAGE_ROOT"
