#!/usr/bin/env bash

OSL_NATIVE_SOUND_PROCESSOR_DIR="${OSL_NATIVE_ADDON_DIR:-Addons/io.sphericals.osl.addons.soundprocessor}"
OSL_NATIVE_SOUND_PROCESSOR_NATIVE_DIR="$OSL_NATIVE_SOUND_PROCESSOR_DIR/Native"

OSL_NATIVE_INCLUDE_DIRS+=(
    "$OSL_NATIVE_SOUND_PROCESSOR_NATIVE_DIR/Devices/Artifact"
    "$OSL_NATIVE_SOUND_PROCESSOR_NATIVE_DIR/Devices/Compressor"
    "$OSL_NATIVE_SOUND_PROCESSOR_NATIVE_DIR/Devices/Delay"
    "$OSL_NATIVE_SOUND_PROCESSOR_NATIVE_DIR/Devices/Reverb"
)

OSL_NATIVE_SOURCES+=(
    "$OSL_NATIVE_SOUND_PROCESSOR_NATIVE_DIR/Devices/Artifact/Artifact.cpp"
    "$OSL_NATIVE_SOUND_PROCESSOR_NATIVE_DIR/Devices/Compressor/Compressor.cpp"
    "$OSL_NATIVE_SOUND_PROCESSOR_NATIVE_DIR/Devices/Delay/Delay.cpp"
    "$OSL_NATIVE_SOUND_PROCESSOR_NATIVE_DIR/Devices/Reverb/Freeverb.cpp"
)
