OSL_NATIVE_SOUND_PROCESSOR_DIR := $(if $(OSL_NATIVE_ADDON_DIR),$(OSL_NATIVE_ADDON_DIR),$(OSL_NATIVE_ADDONS_DIR)/io.sphericals.osl.addons.soundprocessor)
OSL_NATIVE_SOUND_PROCESSOR_NATIVE_DIR := $(OSL_NATIVE_SOUND_PROCESSOR_DIR)/Native

OSL_NATIVE_ADDON_INCLUDE_DIRS += \
    $(LOCAL_PATH)/$(OSL_NATIVE_SOUND_PROCESSOR_NATIVE_DIR)/Devices/Artifact \
    $(LOCAL_PATH)/$(OSL_NATIVE_SOUND_PROCESSOR_NATIVE_DIR)/Devices/Compressor \
    $(LOCAL_PATH)/$(OSL_NATIVE_SOUND_PROCESSOR_NATIVE_DIR)/Devices/Delay \
    $(LOCAL_PATH)/$(OSL_NATIVE_SOUND_PROCESSOR_NATIVE_DIR)/Devices/Reverb

OSL_NATIVE_ADDON_SOURCES += \
    $(OSL_NATIVE_SOUND_PROCESSOR_NATIVE_DIR)/Devices/Artifact/Artifact.cpp \
    $(OSL_NATIVE_SOUND_PROCESSOR_NATIVE_DIR)/Devices/Compressor/Compressor.cpp \
    $(OSL_NATIVE_SOUND_PROCESSOR_NATIVE_DIR)/Devices/Delay/Delay.cpp \
    $(OSL_NATIVE_SOUND_PROCESSOR_NATIVE_DIR)/Devices/Reverb/Freeverb.cpp
